const Category = Object.freeze({
  FOOD: "FOOD",
  SHOPPING: "SHOPPING",
  TRANSPORT: "TRANSPORT",
  ENTERTAINMENT: "ENTERTAINMENT",
  HOME: "HOME",
  FAMILY: "FAMILY",
  HEALTH: "HEALTH",
  PET: "PET",
  TRAVEL: "TRAVEL",
  OTHER: "OTHER",
  FINANCIAL: "FINANCIAL",
  INCOME: "INCOME",
  OTHER_INCOME: "OTHER_INCOME",
});

module.exports = Category;
