const TransactionType = Object.freeze({
  INCOME: "INCOME",
  EXPECTED_INCOME: "EXPECTED_INCOME",
  EXPENSE: "EXPENSE",
  EXPECTED_EXPENSE: "EXPECTED_EXPENSE",
  TRANSFER: "TRANSFER",
  EXPECTED_TRANSFERT: "EXPECTED_TRANSFERT",
  INTEREST: "INTEREST",
});

module.exports = TransactionType;
